#!/usr/bin/fish


	rsrc -manifest res/app.manifest -ico=res/viewer.ico -o res/viewer.syso

# // generated by github.com/dentalwings/rsrc
#
# package main
#
# var exeIDs = map[string]uint16{
#
#         "res/app.manifest": 1,
#         "res/viewer.ico": 2,
# }
