#!/usr/bin/fish


	rsrc -manifest res/app.manifest -ico=res/entry.ico -o res/entry.syso

# // generated by github.com/dentalwings/rsrc
#
# package main
#
# // exeIDs maps the original file names to their resource IDs when embedded in
# // the executable.
# var exeIDs = map[string]uint16{
#
#         "res/app.manifest": 1,
#         "res/entry.ico": 2,
# }
