package main

import (
	"github.com/samuel-jimenez/qc_data_entry/GUI"
)

var (
	WINDOW_WIDTH,
	WINDOW_HEIGHT,
	WINDOW_FUDGE_MARGIN,

	TOP_SPACER_WIDTH,
	TOP_SPACER_HEIGHT,
	INTER_SPACER_HEIGHT,
	BTM_SPACER_WIDTH,
	BTM_SPACER_HEIGHT,

	TOP_PANEL_WIDTH,
	REPRINT_BUTTON_WIDTH,
	TOP_PANEL_INTER_SPACER_WIDTH,

	DATA_UNIT_WIDTH,
	NUM_FIELDS,

	BUTTON_MARGIN,

	GROUP_WIDTH,
	GROUP_HEIGHT,
	GROUP_MARGIN int
)

func refresh_globals(font_size int) {

	GUI.ACCEPT_BUTTON_WIDTH = 50
	GUI.CANCEL_BUTTON_WIDTH = 50

	GUI.GROUPBOX_CUSHION = font_size * 3 / 2
	TOP_SPACER_WIDTH = 7
	TOP_SPACER_HEIGHT = GUI.GROUPBOX_CUSHION + 2
	INTER_SPACER_HEIGHT = 2
	BTM_SPACER_WIDTH = 2
	BTM_SPACER_HEIGHT = 2
	TOP_PANEL_INTER_SPACER_WIDTH = 30

	GUI.LABEL_WIDTH = 10 * font_size
	GUI.PRODUCT_FIELD_WIDTH = 15 * font_size
	GUI.PRODUCT_FIELD_HEIGHT = font_size*16/10 + 8
	GUI.DATA_FIELD_WIDTH = 6 * font_size
	GUI.DATA_SUBFIELD_WIDTH = 5 * font_size
	DATA_UNIT_WIDTH = 4 * font_size
	GUI.DATA_MARGIN = 10

	GUI.SOURCES_LABEL_WIDTH = 15*font_size + GUI.DATA_MARGIN
	GUI.SOURCES_FIELD_WIDTH = 30 * font_size

	GUI.EDIT_FIELD_HEIGHT = 3*font_size - 2
	NUM_FIELDS = 6

	GUI.RANGES_RO_PADDING = 10
	GUI.RANGES_RO_FIELD_WIDTH = 7*font_size/2 + 14
	GUI.RANGES_RO_SPACER_WIDTH = 20
	GUI.RANGES_RO_FIELD_HEIGHT = GUI.EDIT_FIELD_HEIGHT

	GUI.DISCRETE_FIELD_WIDTH = 21 * font_size
	GUI.DISCRETE_FIELD_HEIGHT = font_size * 9 / 2
	GUI.PRODUCT_TYPE_WIDTH = 8*font_size + 90

	GUI.RANGES_FIELD_HEIGHT = font_size*5/2 + 30
	GUI.RANGES_FIELD_SMALL_HEIGHT = font_size * 5 / 2
	GUI.RANGES_FIELD_WIDTH = 200
	GUI.RANGES_BUTTON_WIDTH = 200
	GUI.RANGES_BUTTON_HEIGHT = GUI.RANGES_FIELD_HEIGHT
	GUI.RANGES_BUTTON_MARGIN = 10
	GUI.RANGES_WINDOW_PADDING = 5

	GUI.SMOL_BUTTON_WIDTH = 8 * font_size

	GUI.BUTTON_WIDTH = 10 * font_size
	GUI.BUTTON_HEIGHT = 40

	REPRINT_BUTTON_WIDTH = 10 * font_size

	GROUP_MARGIN = 5
	WINDOW_FUDGE_MARGIN = 16
	BUTTON_MARGIN = 5

	GUI.RANGES_WINDOW_WIDTH = 2*GUI.RANGES_WINDOW_PADDING + 2*GUI.RANGES_PADDING + GUI.LABEL_WIDTH + 3*GUI.RANGES_FIELD_WIDTH + WINDOW_FUDGE_MARGIN
	GUI.RANGES_WINDOW_HEIGHT = GUI.RANGES_WINDOW_PADDING + 3*GUI.RANGES_PADDING + 2*GUI.ERROR_MARGIN + GUI.DISCRETE_FIELD_HEIGHT + 2*GUI.RANGES_FIELD_SMALL_HEIGHT + 7*GUI.RANGES_FIELD_HEIGHT + GUI.RANGES_BUTTON_HEIGHT + WINDOW_FUDGE_MARGIN

	TOP_PANEL_WIDTH = 2*GUI.LABEL_WIDTH + GUI.PRODUCT_FIELD_WIDTH + TOP_PANEL_INTER_SPACER_WIDTH + 2*REPRINT_BUTTON_WIDTH + 4*BUTTON_MARGIN

	GROUP_WIDTH = TOP_SPACER_WIDTH + GUI.LABEL_WIDTH + GUI.DATA_SUBFIELD_WIDTH + DATA_UNIT_WIDTH + GUI.DATA_MARGIN + BTM_SPACER_WIDTH + 2*GUI.ERROR_MARGIN
	GROUP_HEIGHT = TOP_SPACER_HEIGHT +
		NUM_FIELDS*GUI.EDIT_FIELD_HEIGHT + BTM_SPACER_HEIGHT

	GUI.DATA_FIELD_WIDTH = TOP_SPACER_WIDTH + 3*GUI.RANGES_RO_FIELD_WIDTH + 2*GUI.RANGES_RO_SPACER_WIDTH + GUI.RANGES_RO_PADDING

	WINDOW_WIDTH = max(GROUP_MARGIN+2*GROUP_WIDTH+GUI.DATA_FIELD_WIDTH, TOP_PANEL_WIDTH) + WINDOW_FUDGE_MARGIN

	WINDOW_HEIGHT = 30*font_size + 300

}
