package GUI

import (
	"database/sql"
	"strings"

	"github.com/samuel-jimenez/qc_data_entry/DB"
	"github.com/samuel-jimenez/windigo"
	"github.com/samuel-jimenez/windigo/w32"
)

var (
	OFF_AXIS       = 0
	RANGES_PADDING = 10
	LABEL_WIDTH    = 100

	ERROR_MARGIN = 3

	ErroredPen = windigo.Pen_from_flags(w32.PS_GEOMETRIC, 2, windigo.NewSolidColorBrush(windigo.RGB(255, 0, 64)))
	OKPen      = windigo.Pen_from_flags(w32.PS_GEOMETRIC, 2, windigo.NewSystemColorBrush(w32.COLOR_BTNFACE))
)

var WINDOW_WIDTH,
	WINDOW_HEIGHT,
	WINDOW_FUDGE_MARGIN_W,
	WINDOW_FUDGE_MARGIN_H,
	STATUS_BAR_HEIGHT,
	MENU_HEIGHT,

	GROUPBOX_CUSHION,
	TOP_SPACER_WIDTH,
	TOP_SPACER_HEIGHT,
	INTER_SPACER_HEIGHT,
	BTM_SPACER_WIDTH,
	BTM_SPACER_HEIGHT,

	TOP_PANEL_WIDTH,
	HPANEL_WIDTH,
	REPRINT_BUTTON_WIDTH,
	REPRINT_BUTTON_MARGIN_L,

	TOP_PANEL_INTER_SPACER_WIDTH,
	HPANEL_MARGIN,

	RANGE_WIDTH,
	PRODUCT_TYPE_WIDTH,

	PRODUCT_FIELD_WIDTH,
	PRODUCT_FIELD_HEIGHT,
	DATA_FIELD_WIDTH,
	DATA_SUBFIELD_WIDTH,
	DATA_UNIT_WIDTH,
	DATA_MARGIN,
	SOURCES_LABEL_WIDTH,
	SOURCES_FIELD_WIDTH,
	EDIT_FIELD_HEIGHT,
	NUM_FIELDS,

	CLOCK_WIDTH,
	CLOCK_TIMER_WIDTH,
	CLOCK_TIMER_OFFSET_H,

	ACCEPT_BUTTON_WIDTH,
	CANCEL_BUTTON_WIDTH,

	DISCRETE_FIELD_WIDTH,
	DISCRETE_FIELD_HEIGHT,

	RANGES_WINDOW_WIDTH,
	RANGES_WINDOW_HEIGHT,
	RANGES_WINDOW_PADDING,
	RANGES_FIELD_HEIGHT,
	RANGES_FIELD_SMALL_HEIGHT,
	RANGES_FIELD_WIDTH,
	RANGES_BUTTON_WIDTH,
	RANGES_BUTTON_HEIGHT,
	RANGES_BUTTON_MARGIN,

	RANGES_RO_PADDING,
	RANGES_RO_FIELD_WIDTH,
	RANGES_RO_SPACER_WIDTH,
	RANGES_RO_FIELD_HEIGHT,

	SMOL_BUTTON_WIDTH,
	BUTTON_WIDTH,
	BUTTON_HEIGHT,
	BUTTON_MARGIN,

	GROUP_WIDTH,
	GROUP_HEIGHT,
	GROUP_MARGIN int

func Refresh_globals(font_size int) {
	// 	CLOCK_TIMER_WIDTH = 35
	// 	CLOCK_TIMER_OFFSET_H = 10
	// 	CLOCK_WIDTH = 3*CLOCK_TIMER_WIDTH + 4*CLOCK_TIMER_OFFSET_H

	HPANEL_MARGIN = 10

	ACCEPT_BUTTON_WIDTH = 50
	CANCEL_BUTTON_WIDTH = 50

	GROUPBOX_CUSHION = font_size * 3 / 2
	TOP_SPACER_WIDTH = 7
	TOP_SPACER_HEIGHT = GROUPBOX_CUSHION + 2
	INTER_SPACER_HEIGHT = 2
	BTM_SPACER_WIDTH = 2
	BTM_SPACER_HEIGHT = 2
	TOP_PANEL_INTER_SPACER_WIDTH = 30

	LABEL_WIDTH = 10 * font_size
	PRODUCT_FIELD_WIDTH = 15 * font_size
	PRODUCT_FIELD_HEIGHT = font_size*16/10 + 8
	DATA_FIELD_WIDTH = 6 * font_size
	DATA_SUBFIELD_WIDTH = 5 * font_size
	DATA_UNIT_WIDTH = 4 * font_size
	DATA_MARGIN = 10

	SOURCES_LABEL_WIDTH = 15*font_size + DATA_MARGIN
	SOURCES_FIELD_WIDTH = 30 * font_size

	EDIT_FIELD_HEIGHT = 3*font_size - 2
	NUM_FIELDS = 6

	RANGES_RO_PADDING = 10
	RANGES_RO_FIELD_WIDTH = 7*font_size/2 + 14
	RANGES_RO_SPACER_WIDTH = 20
	RANGES_RO_FIELD_HEIGHT = EDIT_FIELD_HEIGHT

	// DISCRETE_FIELD_WIDTH = 28 * font_size // show ISO
	DISCRETE_FIELD_WIDTH = 21 * font_size // hide ISO
	DISCRETE_FIELD_HEIGHT = font_size * 9 / 2
	PRODUCT_TYPE_WIDTH = 8*font_size + 90

	RANGES_FIELD_HEIGHT = font_size*5/2 + 30
	RANGES_FIELD_SMALL_HEIGHT = font_size * 5 / 2
	RANGES_FIELD_WIDTH = 200
	RANGES_BUTTON_WIDTH = 200
	RANGES_BUTTON_HEIGHT = RANGES_FIELD_HEIGHT
	RANGES_BUTTON_MARGIN = 10
	RANGES_WINDOW_PADDING = 5

	SMOL_BUTTON_WIDTH = 7 * font_size

	BUTTON_WIDTH = 10 * font_size
	BUTTON_HEIGHT = 40

	REPRINT_BUTTON_WIDTH = 10 * font_size

	GROUP_MARGIN = 5
	WINDOW_FUDGE_MARGIN_W = 16
	WINDOW_FUDGE_MARGIN_H = 39
	// WINDOW_CHROME_HEIGHT = 39
	STATUS_BAR_HEIGHT = 25

	MENU_HEIGHT = 20
	BUTTON_MARGIN = 5

	REPRINT_BUTTON_MARGIN_L = 2*LABEL_WIDTH + PRODUCT_FIELD_WIDTH + TOP_PANEL_INTER_SPACER_WIDTH - 2*SMOL_BUTTON_WIDTH - DISCRETE_FIELD_WIDTH - 2*BUTTON_MARGIN

	RANGES_WINDOW_WIDTH = 2*RANGES_WINDOW_PADDING + 2*RANGES_PADDING + LABEL_WIDTH + 4*RANGES_FIELD_WIDTH + 2*RANGES_BUTTON_WIDTH + RANGES_BUTTON_WIDTH/2 + WINDOW_FUDGE_MARGIN_W
	RANGES_WINDOW_HEIGHT = RANGES_WINDOW_PADDING + 3*RANGES_PADDING + 2*ERROR_MARGIN + DISCRETE_FIELD_HEIGHT + 2*RANGES_FIELD_SMALL_HEIGHT + 7*RANGES_FIELD_HEIGHT + RANGES_BUTTON_HEIGHT + WINDOW_FUDGE_MARGIN_H

	// 	num_rows := 3
	//
	// 	TOP_SUBPANEL_HEIGHT = TOP_SPACER_HEIGHT + num_rows*(PRODUCT_FIELD_HEIGHT+INTER_SPACER_HEIGHT) + BTM_SPACER_HEIGHT
	// 	TOP_PANEL_HEIGHT = TOP_SUBPANEL_HEIGHT + num_rows*GROUPBOX_CUSHION + PRODUCT_FIELD_HEIGHT
	// 	TOP_PANEL_WIDTH = HPANEL_MARGIN + 2*LABEL_WIDTH + 2*PRODUCT_FIELD_WIDTH + TOP_PANEL_INTER_SPACER_WIDTH + CLOCK_WIDTH
	//
	// 	HPANEL_WIDTH = TOP_PANEL_WIDTH - CLOCK_WIDTH
	//
	// 	GROUP_WIDTH = TOP_SPACER_WIDTH + LABEL_WIDTH + DATA_SUBFIELD_WIDTH + DATA_UNIT_WIDTH + DATA_MARGIN + BTM_SPACER_WIDTH + 2*ERROR_MARGIN
	// 	GROUP_HEIGHT = TOP_SPACER_HEIGHT +
	// 	NUM_FIELDS*EDIT_FIELD_HEIGHT + BTM_SPACER_HEIGHT
	//
	// 	DATA_FIELD_WIDTH = TOP_SPACER_WIDTH + 3*RANGES_RO_FIELD_WIDTH + 2*RANGES_RO_SPACER_WIDTH + RANGES_RO_PADDING
	//
	// 	WINDOW_WIDTH = max(GROUP_MARGIN+2*GROUP_WIDTH+DATA_FIELD_WIDTH, TOP_PANEL_WIDTH) + WINDOW_FUDGE_MARGIN_W
	//
	// 	WINDOW_HEIGHT = TOP_PANEL_HEIGHT + PRODUCT_FIELD_HEIGHT + TOP_SPACER_HEIGHT + GROUP_HEIGHT + GROUP_MARGIN + BTM_SPACER_HEIGHT + BUTTON_HEIGHT + EDIT_FIELD_HEIGHT + 2*PRODUCT_FIELD_HEIGHT + PRODUCT_FIELD_HEIGHT + WINDOW_FUDGE_MARGIN_W
}

func Fill_combobox_from_query_rows(control windigo.ComboBoxable, fn func(row *sql.Rows) error, select_statement *sql.Stmt, args ...any) {
	i := 0
	DB.Forall_err("fill_combobox_from_query",
		func() {
			control.DeleteAllItems()
		},
		func(row *sql.Rows) error {
			i++
			return fn(row)
		},
		select_statement, args...)
	if i == 1 {
		control.SetSelectedItem(0)
	}
}

func Fill_combobox_from_query_fn(control windigo.ComboBoxable, fn func(int, string), select_statement *sql.Stmt, args ...any) {
	i := 0
	DB.Forall_err("fill_combobox_from_query",
		func() {
			control.DeleteAllItems()
		},
		func(row *sql.Rows) error {
			var (
				id   int
				name string
			)

			if err := row.Scan(
				&id, &name,
			); err != nil {
				return err
			}
			fn(id, name)
			i++
			return nil
		},
		select_statement, args...)
	if i == 1 {
		control.SetSelectedItem(0)
	}
}

func Fill_combobox_from_query(control windigo.ComboBoxable, select_statement *sql.Stmt, args ...any) {
	Fill_combobox_from_query_fn(control, func(id int, name string) { control.AddItem(name) }, select_statement, args...)
}

func STRING_UPCASE(field windigo.BaseController) {
	field.SetText(strings.ToUpper(strings.TrimSpace(field.Text())))
}
