package qc

import (
	"github.com/samuel-jimenez/qc_data_entry/GUI"
)

var (
	WINDOW_WIDTH,
	WINDOW_HEIGHT,
	WINDOW_FUDGE_MARGIN,

	NUM_FIELDS,

	BUTTON_MARGIN int

	VISUAL_TEXT = "Visual Inspection"
	STRING_TEXT = "String"

	SUBMIT_TEXT = "Submit"
	CLEAR_TEXT  = "Clear"
	LOG_TEXT    = "Log"

	SUBMIT_CLEAR_BTN     = []string{SUBMIT_TEXT, CLEAR_TEXT}
	SUBMIT_CLEAR_LOG_BTN = []string{SUBMIT_TEXT, CLEAR_TEXT, LOG_TEXT}
)

func Refresh_globals(font_size int) {

	GUI.CLOCK_TIMER_WIDTH = 35
	GUI.CLOCK_TIMER_OFFSET_H = 10
	GUI.CLOCK_WIDTH = 3*GUI.CLOCK_TIMER_WIDTH + 4*GUI.CLOCK_TIMER_OFFSET_H

	GUI.HPANEL_MARGIN = 10

	GUI.ACCEPT_BUTTON_WIDTH = 50
	GUI.CANCEL_BUTTON_WIDTH = 50

	GUI.GROUPBOX_CUSHION = font_size * 3 / 2
	GUI.TOP_SPACER_WIDTH = 7
	GUI.TOP_SPACER_HEIGHT = GUI.GROUPBOX_CUSHION + 2
	GUI.INTER_SPACER_HEIGHT = 2
	GUI.BTM_SPACER_WIDTH = 2
	GUI.BTM_SPACER_HEIGHT = 2
	GUI.TOP_PANEL_INTER_SPACER_WIDTH = 30

	GUI.LABEL_WIDTH = 10 * font_size
	GUI.PRODUCT_FIELD_WIDTH = 15 * font_size
	GUI.PRODUCT_FIELD_HEIGHT = font_size*16/10 + 8
	GUI.DATA_FIELD_WIDTH = 6 * font_size
	GUI.DATA_SUBFIELD_WIDTH = 5 * font_size
	GUI.DATA_UNIT_WIDTH = 4 * font_size
	GUI.DATA_MARGIN = 10

	GUI.SOURCES_LABEL_WIDTH = 15*font_size + GUI.DATA_MARGIN
	GUI.SOURCES_FIELD_WIDTH = 30 * font_size

	GUI.EDIT_FIELD_HEIGHT = 3*font_size - 2
	NUM_FIELDS = 6

	GUI.RANGES_RO_PADDING = 10
	GUI.RANGES_RO_FIELD_WIDTH = 7*font_size/2 + 14
	GUI.RANGES_RO_SPACER_WIDTH = 20
	GUI.RANGES_RO_FIELD_HEIGHT = GUI.EDIT_FIELD_HEIGHT

	// GUI.DISCRETE_FIELD_WIDTH = 28 * font_size // show ISO
	GUI.DISCRETE_FIELD_WIDTH = 21 * font_size // hide ISO
	GUI.DISCRETE_FIELD_HEIGHT = font_size * 9 / 2
	GUI.PRODUCT_TYPE_WIDTH = 8*font_size + 90

	GUI.RANGES_FIELD_HEIGHT = font_size*5/2 + 30
	GUI.RANGES_FIELD_SMALL_HEIGHT = font_size * 5 / 2
	GUI.RANGES_FIELD_WIDTH = 200
	GUI.RANGES_BUTTON_WIDTH = 200
	GUI.RANGES_BUTTON_HEIGHT = GUI.RANGES_FIELD_HEIGHT
	GUI.RANGES_BUTTON_MARGIN = 10
	GUI.RANGES_WINDOW_PADDING = 5

	GUI.SMOL_BUTTON_WIDTH = 8 * font_size

	GUI.BUTTON_WIDTH = 10 * font_size
	GUI.BUTTON_HEIGHT = 40

	GUI.REPRINT_BUTTON_WIDTH = 10 * font_size

	GUI.GROUP_MARGIN = 5
	WINDOW_FUDGE_MARGIN = 16
	BUTTON_MARGIN = 5

	GUI.REPRINT_BUTTON_MARGIN_L = 2*GUI.LABEL_WIDTH + GUI.PRODUCT_FIELD_WIDTH + GUI.TOP_PANEL_INTER_SPACER_WIDTH - GUI.SMOL_BUTTON_WIDTH - GUI.DISCRETE_FIELD_WIDTH

	GUI.RANGES_WINDOW_WIDTH = 2*GUI.RANGES_WINDOW_PADDING + 2*GUI.RANGES_PADDING + GUI.LABEL_WIDTH + 3*GUI.RANGES_FIELD_WIDTH + WINDOW_FUDGE_MARGIN
	GUI.RANGES_WINDOW_HEIGHT = GUI.RANGES_WINDOW_PADDING + 3*GUI.RANGES_PADDING + 2*GUI.ERROR_MARGIN + GUI.DISCRETE_FIELD_HEIGHT + 2*GUI.RANGES_FIELD_SMALL_HEIGHT + 7*GUI.RANGES_FIELD_HEIGHT + GUI.RANGES_BUTTON_HEIGHT + WINDOW_FUDGE_MARGIN

	GUI.TOP_PANEL_WIDTH = GUI.HPANEL_MARGIN + 2*GUI.LABEL_WIDTH + 2*GUI.PRODUCT_FIELD_WIDTH + GUI.TOP_PANEL_INTER_SPACER_WIDTH + GUI.CLOCK_WIDTH

	GUI.HPANEL_WIDTH = GUI.TOP_PANEL_WIDTH - GUI.CLOCK_WIDTH

	GUI.GROUP_WIDTH = GUI.TOP_SPACER_WIDTH + GUI.LABEL_WIDTH + GUI.DATA_SUBFIELD_WIDTH + GUI.DATA_UNIT_WIDTH + GUI.DATA_MARGIN + GUI.BTM_SPACER_WIDTH + 2*GUI.ERROR_MARGIN
	GUI.GROUP_HEIGHT = GUI.TOP_SPACER_HEIGHT +
		NUM_FIELDS*GUI.EDIT_FIELD_HEIGHT + GUI.BTM_SPACER_HEIGHT

	GUI.DATA_FIELD_WIDTH = GUI.TOP_SPACER_WIDTH + 3*GUI.RANGES_RO_FIELD_WIDTH + 2*GUI.RANGES_RO_SPACER_WIDTH + GUI.RANGES_RO_PADDING

	WINDOW_WIDTH = max(GUI.GROUP_MARGIN+2*GUI.GROUP_WIDTH+GUI.DATA_FIELD_WIDTH, GUI.TOP_PANEL_WIDTH) + WINDOW_FUDGE_MARGIN

	WINDOW_HEIGHT = 30*font_size + 300

}
