package qc

import (
	"github.com/samuel-jimenez/qc_data_entry/GUI"
)

var (
	WINDOW_WIDTH,
	WINDOW_HEIGHT,

	TOP_PANEL_HEIGHT,
	TOP_SUBPANEL_HEIGHT,

	CONTAINER_ITEM_WIDTH,

	NUM_FIELDS,

	BUTTON_MARGIN int

	VISUAL_TEXT = "Visual Inspection"

	SUBMIT_TEXT = "Submit"
	CLEAR_TEXT  = "Clear"
	LOG_TEXT    = "Log"

	SUBMIT_CLEAR_LOG_BTN = []string{SUBMIT_TEXT, CLEAR_TEXT, LOG_TEXT}
)

func Refresh_globals(font_size int) {
	GUI.Refresh_globals(font_size)

	GUI.CLOCK_TIMER_WIDTH = 5 * font_size
	GUI.CLOCK_TIMER_OFFSET_H = 1 * font_size
	GUI.CLOCK_WIDTH = 3*GUI.CLOCK_TIMER_WIDTH + 4*GUI.CLOCK_TIMER_OFFSET_H

	CONTAINER_ITEM_WIDTH = 6 * font_size

	NUM_FIELDS = 6
	BUTTON_MARGIN = 5

	num_rows := 3

	TOP_SUBPANEL_HEIGHT = GUI.TOP_SPACER_HEIGHT + num_rows*(GUI.PRODUCT_FIELD_HEIGHT+GUI.INTER_SPACER_HEIGHT) + GUI.BTM_SPACER_HEIGHT
	TOP_PANEL_HEIGHT = TOP_SUBPANEL_HEIGHT + num_rows*GUI.GROUPBOX_CUSHION + GUI.PRODUCT_FIELD_HEIGHT
	GUI.TOP_PANEL_WIDTH = GUI.HPANEL_MARGIN + 2*GUI.LABEL_WIDTH + 2*GUI.PRODUCT_FIELD_WIDTH + GUI.TOP_PANEL_INTER_SPACER_WIDTH + GUI.CLOCK_WIDTH

	GUI.HPANEL_WIDTH = GUI.TOP_PANEL_WIDTH - GUI.CLOCK_WIDTH

	GUI.GROUP_WIDTH = GUI.TOP_SPACER_WIDTH + GUI.LABEL_WIDTH + GUI.DATA_SUBFIELD_WIDTH + GUI.DATA_UNIT_WIDTH + GUI.DATA_MARGIN + GUI.BTM_SPACER_WIDTH + 2*GUI.ERROR_MARGIN
	GUI.GROUP_HEIGHT = GUI.TOP_SPACER_HEIGHT +
		NUM_FIELDS*GUI.EDIT_FIELD_HEIGHT + GUI.BTM_SPACER_HEIGHT

	GUI.DATA_FIELD_WIDTH = GUI.TOP_SPACER_WIDTH + 3*GUI.RANGES_RO_FIELD_WIDTH + 2*GUI.RANGES_RO_SPACER_WIDTH + GUI.RANGES_RO_PADDING

	WINDOW_WIDTH = max(GUI.GROUP_MARGIN+2*GUI.GROUP_WIDTH+GUI.DATA_FIELD_WIDTH, GUI.TOP_PANEL_WIDTH) + GUI.WINDOW_FUDGE_MARGIN_W

	WINDOW_HEIGHT = TOP_PANEL_HEIGHT + GUI.PRODUCT_FIELD_HEIGHT + GUI.TOP_SPACER_HEIGHT + GUI.GROUP_HEIGHT + GUI.GROUP_MARGIN + GUI.BTM_SPACER_HEIGHT + GUI.BUTTON_HEIGHT + GUI.EDIT_FIELD_HEIGHT + 2*GUI.PRODUCT_FIELD_HEIGHT + GUI.DATA_MARGIN + GUI.WINDOW_FUDGE_MARGIN_H
}
